<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #1f2937; padding: 32px; }
        h1  { font-size: 20px; font-weight: bold; margin-bottom: 4px; }
        .subtitle { color: #6b7280; font-size: 11px; margin-bottom: 24px; }
        .meta { margin-bottom: 24px; padding: 12px 16px; background: #f3f4f6; border-radius: 6px; }
        .meta p { margin-bottom: 4px; }
        .meta strong { font-weight: 600; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        thead th { background: #4f46e5; color: #fff; padding: 8px 12px; text-align: left; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; }
        tbody tr:nth-child(even) { background: #f9fafb; }
        tbody td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
        .badge { display: inline-block; padding: 1px 6px; border-radius: 9999px; font-size: 9px; font-weight: 600; text-transform: uppercase; background: #e0e7ff; color: #4338ca; }
        .footer { margin-top: 32px; font-size: 10px; color: #9ca3af; text-align: center; }
    </style>
</head>
<body>

    <h1>{{ $survey->title }}</h1>
    <p class="subtitle">Submission Report — AuditHub</p>

    <div class="meta">
        <p><strong>Submission ID:</strong> {{ $submission->uuid }}</p>
        <p><strong>Submitted:</strong> {{ $submission->submitted_at?->format('d/m/Y H:i') }}</p>
        @if($survey->description)
        <p><strong>Survey:</strong> {{ $survey->description }}</p>
        @endif
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 35%">Question</th>
                <th style="width: 15%">Type</th>
                <th>Answer</th>
            </tr>
        </thead>
        <tbody>
            @forelse($rows as $row)
            <tr>
                <td>{{ $row['label'] }}</td>
                <td><span class="badge">{{ $row['type'] }}</span></td>
                <td>
                    @if($row['type'] === 'file')
                        <em style="color:#6b7280">[attachment]</em>
                    @elseif($row['answer'] === null || $row['answer'] === '')
                        <em style="color:#9ca3af">—</em>
                    @else
                        {{ $row['answer'] }}
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="3" style="text-align:center;color:#9ca3af">No answers recorded.</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <p class="footer">Generated by AuditHub &bull; {{ now()->format('d/m/Y H:i') }}</p>

</body>
</html>
